### ISSUE TITLE
社区标题里标点符号不能正常显示

### ISSUE THREAD

**Issue by echochen0870** [Rokid/NextForum#11]
如下图所示，标题的标点会错误显示~
![2018-05-03 1 35 21](https://user-images.githubusercontent.com/29083738/39561277-46a56742-4ed7-11e8-8d0f-fbf258f8ce68.png)
![2018-05-03 1 35 35](https://user-images.githubusercontent.com/29083738/39561279-47023b2a-4ed7-11e8-9759-81946070d03f.png)

**Comment by yorkie** [comment]
标题改用 `v-html` 方式渲染 :)
