### ISSUE TITLE
帖子发布之后进行修改 编辑器中内容为空

### ISSUE THREAD

**Issue by echochen0870** [Rokid/NextForum#9]
帖子发布之后进行修改 编辑器中内容为空，如下图显示
![2018-04-24 10 14 26](https://user-images.githubusercontent.com/29083738/39162527-93a50434-47a8-11e8-8864-c48f335a5bfd.png)
![2018-04-24 10 14 30](https://user-images.githubusercontent.com/29083738/39162534-9bad21d4-47a8-11e8-8d56-01f987ab4ebd.png)

**Comment by yorkie** [comment]
@echochen0870 这个链接给我一个～
